### **Diferencias**
Las matrices numpy son **estrictamente bidimensionales**, mientras que las matrices numpy (ndarrays) **son N-dimensionales**.  

Los objetos Matrix son una **subclase de ndarray**, por lo que heredan todos los atributos y métodos de ndarrays. 

Tanto los objetos de matriz como los  array tienen **.T** para devolver la transposición, pero los objetos de matriz también tienen **.H** para la transposición conjugada y **.I** para la inversa. 



In [2]:
import numpy as np

In [3]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [4]:
def relu(x):
    print(np.maximum(0, x))
    return np.maximum(0, x)

## **EJEMPLO**

In [5]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
print(X)
print(H1_W)
print(H1)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
print(H1)
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
print(OL)

[[0.1 0.2]
 [1.  2. ]]
[[ 0.25 -8.  ]
 [ 0.37 14.  ]]
[[ 0.099  2.   ]
 [ 0.99  20.   ]]
[[0.52472981 0.88079708]
 [0.72908792 1.        ]]
[[0.99995577]
 [0.99999332]]


## **EJERCICIO**

In [8]:
def neural_network(X):
    H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])

    OL_W = np.array([[0.116],[0.329],[0.708]])

    #X =  np.array([[1,1]]) VECTOR DE PRUEBA

    H1 = np.matmul(X,H1_W)
    H1 = relu(H1)#sigmoid(H1)#
    print(H1)
    OL = np.matmul(H1,OL_W)
    OL = relu(OL)#sigmoid(OL)#
    #print(OL)
    return OL

In [12]:
#neural_network([1,1])
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

res = neural_network(X)
#res = neural_network([1,1])
#print(res)


[[2.9520e-01 1.7455e+00 9.6280e-01]
 [2.6400e-01 4.9125e-01 2.9100e-01]
 [4.5680e+00 9.4700e+00 5.5520e+00]
 [9.2160e+00 9.3900e+00 6.0240e+00]
 [5.5440e+00 6.7600e+00 4.2160e+00]
 [3.0320e-01 7.9050e-01 4.5480e-01]
 [9.1040e+00 8.5350e+00 5.5560e+00]
 [9.3600e+01 2.0650e+02 1.2040e+02]
 [5.8800e+00 9.3250e+00 5.6200e+00]
 [3.8160e+02 1.3890e+03 7.8240e+02]]
[[2.9520e-01 1.7455e+00 9.6280e-01]
 [2.6400e-01 4.9125e-01 2.9100e-01]
 [4.5680e+00 9.4700e+00 5.5520e+00]
 [9.2160e+00 9.3900e+00 6.0240e+00]
 [5.5440e+00 6.7600e+00 4.2160e+00]
 [3.0320e-01 7.9050e-01 4.5480e-01]
 [9.1040e+00 8.5350e+00 5.5560e+00]
 [9.3600e+01 2.0650e+02 1.2040e+02]
 [5.8800e+00 9.3250e+00 5.6200e+00]
 [3.8160e+02 1.3890e+03 7.8240e+02]]
[[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]


In [10]:
Xtest = np.array([[1,1]])
print(neural_network(Xtest))

[[0.824 1.21  0.736]]
[[0.824 1.21  0.736]]
[[1.014762]]
[[1.014762]]
