### **Diferencias**
Las matrices numpy son **estrictamente bidimensionales**, mientras que las matrices numpy (ndarrays) **son N-dimensionales**.  

Los objetos Matrix son una **subclase de ndarray**, por lo que heredan todos los atributos y métodos de ndarrays. 

Tanto los objetos de matriz como los  array tienen **.T** para devolver la transposición, pero los objetos de matriz también tienen **.H** para la transposición conjugada y **.I** para la inversa. 



In [4]:
import numpy as np

In [8]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

## **EJEMPLO**

In [12]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
print(X)
print(H1_W)
print(H1)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
print(H1)
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
print(OL)

[[0.1 0.2]
 [1.  2. ]]
[[ 0.25 -8.  ]
 [ 0.37 14.  ]]
[[ 0.099  2.   ]
 [ 0.99  20.   ]]
[[0.52472981 0.88079708]
 [0.72908792 1.        ]]
[[0.99995577]
 [0.99999332]]


## **EJERCICIO**

In [85]:
def neural_network(x):
    H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])

    OL_W = np.array([[0.116],[0.329],[0.708]])

    #X =  np.array([[1,1]]) VECTOR DE PRUEBA

    H1 = np.matmul(X,H1_W)
    H1 = sigmoid(H1)
    OL = np.matmul(H1,OL_W)
    OL = sigmoid(OL)
    #print(OL)
    return OL

In [86]:
#neural_network([1,1])
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

res = neural_network(X)
print(res)


[[0.70244573]
 [0.66259284]
 [0.75933678]
 [0.75973948]
 [0.75802295]
 [0.6739704 ]
 [0.75954693]
 [0.76005845]
 [0.75952743]
 [0.76005845]]
